version: "3.9"
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: test_runserver
    env_file:
      - web/.env
    environment:
      - PORT=8020
    ports:
      - "8000:8000"
    # command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - static:/app/static
      - ./web:/app:ro
  postgres_db:
    image: postgres
    restart: always
    command: -p 5433
    env_file:
      - web/.env
    expose:
      - 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static:
