services:
  nginx:
    depends_on:
      - web
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - staticfiles:/home/app/staticfiles
      
  web:
    depends_on:
      - postgres_db
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    environment:
      - PORT=8000
    volumes:
      - staticfiles:/app/staticfiles
      # - ./web:/app

  postgres_db:
    image: postgres
    restart: always
    command: -p 5433
    env_file:
      - web/.env
    expose:
      - 5433
    ports:
      - 5433:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  staticfiles: